### ISSUE TITLE
[backport] Print code coverage ratio in command output

### ISSUE THREAD

**Issue by nmad** [leanphp/phpspec-code-coverage#1]
> Hi,
>
> Don't know if it is possible, but could be handful for CI.

@erichard opened this Issue on 24 Nov 2016 on https://github.com/henrikbjorn/PhpSpecCodeCoverageExtension/issues/60

**Comment by ek9** [comment]
For this information the `text` report can be used as it will print report summary in the command line:

![text report](https://i.imgur.com/e01Xfvw.png)

Closing.
