### ISSUE TITLE
PHPSpec v4 support

### ISSUE THREAD

**Issue by DavidGarciaCat** [leanphp/phpspec-code-coverage#13]
Could be possible to add please support for `phpspec/phpspec` v4?

**Comment by JurRutten** [comment]
+1

**Comment by N-M** [comment]
There is pull request for v4 [https://github.com/leanphp/phpspec-code-coverage/pull/10](url)

**Comment by DavidGarciaCat** [comment]
Thanks @N-M for the link, hope we can see it merged soon

**Comment by ek9** [comment]
The PR ( #10 ) has been merged and `v4.0.0` has been released today. It brings PhpSpec v4 support (PHP 7+ only). As the implementation is done I will close the issue. If you find any issues regarding the `v4`, do not hesitate to open an issue.

Thank you for contributions.

**Comment by DavidGarciaCat** [comment]
Thanks @ek9 !!
