### ISSUE TITLE
Should this package work with PhpSpec code generation?

### ISSUE THREAD

**Issue by drupsys** [leanphp/phpspec-code-coverage#15]
PhpSpec crashes with code generation enabled, I was just wondering if that is a known issue?

**Comment by ek9** [comment]
Hi @drupsys

Yes, the package should be (and is) working. We have travis CI setuo for that and I am using it personally.

Could you please provide more information on the OS and environment that you run this on? Also the directory structure and configuration file would be handy to help you set things up correctly.

**Comment by ek9** [comment]
Closing as we have no more information from you. The package is in a working and coverage can be generated.

p.s. A user recently reported that he had problems due to `memory_limit` set (see #18 and a note regarding that in README for more information).
