### ISSUE TITLE
phpunit/php-code-coverage v6 support

### ISSUE THREAD

**Issue by ek9** [leanphp/phpspec-code-coverage#19]
This is main issue to track changes to the package related to `phpunit/php-code-coverage:~6.0`

Please do not hesitate to provide any feedback

**Comment by ek9** [comment]
I have investigated and while there were no functional changes in php-code-coverage v6, the release of `6.0.0` made all of the classes of php-code-coverage marked as final (see https://github.com/sebastianbergmann/php-code-coverage/blob/master/ChangeLog-6.0.md )

This breaks PhpSpec tests as it is problematic for `phpspec/prophecy` to create objects mocks from final classes.

This is not really a limitation but merely exposes this packages poor testing architecture. The tests that are now in PhpSpec are integration (functional) tests and should be either restructured or moved to phpunit.

Will update once I have a solution for this.

**Comment by ek9** [comment]
`v4.2.0` has support for `phpunit/php-code-coverage:~6.0`.
As a result of update some of our functional tests were disbaled (needs rewrite) - see #25 
Closing.

**Comment by drupol** [comment]
How about adding an interface to those final classes ?

This would fix all the issues.
